### ISSUE TITLE
GSON Templates will not resolve based on content type when rendering from controller

### ISSUE THREAD

**Issue by csoete** [grails/grails-views#28] opened 2016-04-19 10:41 UTC
Templates will not be resolved based on content type when rendering from controller:

`render(contentType:"text/json", template: "/company/company", model:[company:company])`
will produce (instead of trying to load existing file `_company.gson`):
`Template not found for name [/company/company] and path [/company/_company.gsp]`

_Workaround_
Create dummy view with:
`
model {
    Company company
}
json tmpl."/company/company"(company)
`
and render as view:
`render(contentType:"text/json", view: "/company/company", model:[company:company])`

**Comment by ColinHarrington** [comment] 2016-05-23 21:15
FYI, the issue is with the absolute template URI.

**Comment by ColinHarrington** [comment] 2016-05-31 21:57
Fixed in Grails 3.1.8

**Closed** 2016-05-31 21:57 UTC
