### ISSUE TITLE
Different Content-Type header depending on whether you use respond or render

### ISSUE THREAD

**Issue by marcoscarceles** [grails/grails-views#99] opened 2016-11-22 15:48 UTC
Not sure whether this is considered a defect, but I think it's worth mentioning.

After updating to version `1.1.2` from `1.0.12` when using JSON Views (.gson) the `Content-Type` in the response varies depending on whether you use
```respond myInstance, view: "myView", model: [instance: myInstance, ..., more: data]```
(in which case `application/json` is sent)
or 
```render view: "myView", model: [instace: myInstance, ..., more: data]```
(in which case `text/html` is sent)

In version `1.0.12` both responses had `Cotent-Type: application/json`.

In our case we changed all our `render` to `respond`, so not a real problem for us.

**Comment by jameskleeh** [comment] 2016-11-22 16:17
Duplicate of https://github.com/grails/grails-views/issues/93

**Closed by jameskleeh** 2016-11-22 16:17 UTC
Labels: duplicate
