### ISSUE TITLE
Support for unescaped Unicode in json views

### ISSUE THREAD

**Issue by rasmusrask** [grails/grails-views#71] opened 2016-09-19 09:21 UTC
Right now, the only way to output unescaped JSON, is to wrap all Strings in the `JsonOutput.JsonUnescaped` Class. Otherwise, any control character or Unicode character is escaped in the `JsonOutput#writeObject(Object object, CharBuf buffer)` method.
Would it be possible only to escape the control characters, so the JSON is human-readable, either by configuration or in general?

**Comment by graemerocher** [comment] 2016-09-19 09:50
Could you provide an example JSON view that reproduces the issue?

**Comment by rasmusrask** [comment] 2016-09-19 11:17
This test will fail (using 1.1.0.RC3):

```
    void "Test render a raw GSON view"() {
        when:"A gson view is rendered"
            JsonRenderResult result = render '''
        json {
            message "æøå ÆØÅ"
        }
'''
        then:"The json is correct"
            result.jsonText == '''{"message":"æøå ÆØÅ"}'''
    }
```
Result:
```
Condition not satisfied:

result.jsonText == '''{"message":"æøå ÆØÅ"}'''
|      |        |
|      |        false
|      |        36 differences (29% similarity)
|      |        {"message":"(\\u00e6\\u00f8\\u00e5) (\\u00c6\\u00d8\\u00c5)"}
|      |        {"message":"(æ~øå----~------~-----) (Æ~ØÅ----~------~-----)"}
|      {"message":"\u00e6\u00f8\u00e5 \u00c6\u00d8\u00c5"}
grails.plugin.json.view.test.JsonRenderResult(200, OK, null, [:], [message:æøå ÆØÅ], {"message":"\u00e6\u00f8\u00e5 \u00c6\u00d8\u00c5"})

```

**Comment by graemerocher** [comment] 2016-09-19 12:15
The issue would be to do this in a performant and consistent way since you would have to add a check for each output value. 

In the meantime you can of course static import the `unescaped` method which makes it more readable in the views:

```groovy
import static grails.plugin.json.builder.JsonOutput.*

        json {
            message unescaped("æøå ÆØÅ")
        }
```

**Comment by rasmusrask** [comment] 2016-09-19 14:49
Yes, but then we would have to do that for every attribute in every view.
Also, the `unescaped` method doesn't add quotation marks around the string and we would have to escape inline quotation marks. But that's just wrapping the method in another method :-)

It would be nice if only the control characters were escaped and you could configure whether to escape unicode characters or not.

**Comment by jarl-dk** [comment] 2016-09-19 18:57
The title is a bit misleading, a better title would be "Non-ascii characters are not encoded correct". A correct encoding of JSON is either UTF-8, UTF-16 (BE or LE), or UTF-32 (BE or LE). Preferably UTF-8, see

https://tools.ietf.org/html/rfc7159#section-8.1
https://tools.ietf.org/html/rfc4627#section-3

**Comment by jarl-dk** [comment] 2016-09-19 19:40
@rasmusrask has pointed out that the current implementation is actually not an incorrect serialization of strings because section 7 says "Any character may be escaped", see https://tools.ietf.org/html/rfc7159#section-7
So the title is not so bad after all. What is wanted is an implementation that does not escape more than necessary (only few cases are necessary, see section 7). It is waste of bytes and makes the produced JSON less readable.

**Comment by graemerocher** [comment] 2016-09-21 10:17
Relates to http://stackoverflow.com/questions/9806246/switch-off-utf-escaping-in-jsonbuilder

As discussed in that stackoverflow question, the bytes are exactly the same, so there is no waste of bytes. So the only issue is around readability and for that the implications of the change are too great as we would have to fork large parts of Groovy's JSON APIs.

I'm going to raise the question with the Groovy community and discuss ways to take this issue forward.

**Comment by jarl-dk** [comment] 2016-09-23 08:01
> As discussed in that stackoverflow question, the bytes are exactly the same, so there is no waste of bytes.

That is only correct when you evaluate the JSON as a Javascript expression (possibly even as Java expression) and consider the string literals. Not when you send the JSON over the (HTTP) wire, in that case there is a difference on content-length.

Anyway, agreeing on this is not important.

**Comment by graemerocher** [comment] 2016-09-23 08:05
Just to clarify, I didn't say it isn't important, just that the fix is complex because it would require changes to Groovy's core JSON APIs which is why I'm discussing it with the community.

**Comment by graemerocher** [comment] 2016-09-23 08:06
For reference here is the Groovy issue that we depend on for this fix https://issues.apache.org/jira/browse/GROOVY-6975

**Comment by jarl-dk** [comment] 2016-09-27 13:59
@graemerocher : Thanks for the investigation and link.

**Comment by jameskleeh** [comment] 2016-10-25 17:05
Fixed by https://github.com/grails/grails-views/commit/d31f5159e983659965960b7c6ccc440e37cf8518

**Closed by jameskleeh** 2016-10-25 17:05 UTC
Labels: enhancement, jsonapi
